window.BALE_PAY_LANDING = window.BALE_PAY_LANDING || {};

window.BALE_PAY_LANDING.GROUPS = {
  persian: "ایرانی",
  paper: "کاغذ و چاپ",
  modern: "مدرن و مینیمال",
  dark: "تاریک و نئون",
  retro: "رترو و بازی",
  nature: "طبیعت",
  luxe: "لوکس و فلز",
};

window.BALE_PAY_LANDING.GROUP_ORDER = [
  "persian",
  "paper",
  "modern",
  "dark",
  "retro",
  "nature",
  "luxe",
];

window.BALE_PAY_LANDING.GROUP_PITCH = {
  persian: "کاشی، فرش، فیروزه، یلدا و نوروز — ظاهر پرداخت مثل ویترین یک حجره است.",
  paper: "قبض پاره‌شو، دفتر حساب، بلیت سفر و مُهر لاکی؛ حس کاغذ واقعی داخل مینی‌اپ.",
  modern: "از بانک رسمی تا بروتالیست زرد؛ برای فروشگاهی که می‌خواهد مینیمال یا جسور باشد.",
  dark: "نئون شب، کهکشان، شفق و هولوگرام؛ مناسب برندهای شبانه و دیجیتال.",
  retro: "ماتریکس، آرکید، VHS و تمبر پستی؛ پرداخت با حال‌وهوای بازی و نوستالژی.",
  nature: "جنگل، اقیانوس، کویر، شکوفه و غروب؛ رنگ از خودِ طبیعت می‌آید.",
  luxe: "گاوصندوق، شمش طلا، مرمر و کربن؛ برای کالای گران و فروش خاص.",
};

window.BALE_PAY_LANDING.THEMES = [
  {
    id: "receipt",
    label: "قبض بازار",
    group: "paper",
    desc: "رسید کاغذی با لبه سوراخ‌دار",
    colors: {
      bg: "#c9b491",
      surface: "#f6f1e6",
      ink: "#191f1a",
      muted: "#55605a",
      accent: "#0e6b58",
      accent_ink: "#ffffff",
      amount: "#0b5348",
      danger: "#b42318",
      success: "#0e6b58",
      line: "#c6bba8",
    },
  },
  {
    id: "ledger",
    label: "دفتر حساب",
    group: "paper",
    desc: "خط قرمز حاشیه و ردیف‌های حسابداری",
    colors: {
      bg: "#e6e1d4",
      surface: "#fbf8ef",
      ink: "#222222",
      muted: "#615b50",
      accent: "#1f3a5f",
      accent_ink: "#ffffff",
      amount: "#8b1e1e",
      danger: "#8b1e1e",
      success: "#1f5a3a",
      line: "#d2cbb8",
    },
  },
  {
    id: "wax",
    label: "مُهر لاکی",
    group: "paper",
    desc: "کاغذ کهنه و دکمه‌ای مثل مهر موم",
    colors: {
      bg: "#c8b48a",
      surface: "#f6ecd4",
      ink: "#2b2116",
      muted: "#68563e",
      accent: "#8e1d2c",
      accent_ink: "#fff4e8",
      amount: "#6d1520",
      danger: "#8e1d2c",
      success: "#2f6b3a",
      line: "#d7c49a",
    },
  },
  {
    id: "ticket",
    label: "بلیت سفر",
    group: "paper",
    desc: "بلیت پاره‌شو با ته‌بلیط و بارکد",
    colors: {
      bg: "#14261c",
      surface: "#fffdf6",
      ink: "#17301f",
      muted: "#55655a",
      accent: "#c8461f",
      accent_ink: "#fffaf4",
      amount: "#a83a17",
      danger: "#c0392b",
      success: "#2d6a4f",
      line: "#e4dcc8",
    },
  },
  {
    id: "nastaliq",
    label: "خوشنویسی",
    group: "paper",
    desc: "کاغذ کاهی، جوهر مشکی و شنگرف",
    colors: {
      bg: "#efe7d5",
      surface: "#fdfaf2",
      ink: "#14110c",
      muted: "#665d4e",
      accent: "#1f1b14",
      accent_ink: "#f7f2e6",
      amount: "#7a1f1f",
      danger: "#8b1a1a",
      success: "#2d5a3d",
      line: "#d8cdb6",
    },
  },
  {
    id: "tile",
    label: "کاشی ایرانی",
    group: "persian",
    desc: "هندسه کاشی، لاجورد و فیروزه",
    colors: {
      bg: "#12324a",
      surface: "#f7f1e4",
      ink: "#12202b",
      muted: "#48606e",
      accent: "#0b6c6b",
      accent_ink: "#ffffff",
      amount: "#0b4f6c",
      danger: "#c0392b",
      success: "#0b6c6b",
      line: "#c5b89a",
    },
  },
  {
    id: "rug",
    label: "فرش دستباف",
    group: "persian",
    desc: "زمینه لاکی با حاشیه بافت فرش",
    colors: {
      bg: "#5b1a1a",
      surface: "#f7ecd9",
      ink: "#2b1410",
      muted: "#75574a",
      accent: "#9c2b2b",
      accent_ink: "#fff4e6",
      amount: "#7b1e1e",
      danger: "#a32020",
      success: "#2f6b4a",
      line: "#d9c3a3",
    },
  },
  {
    id: "turquoise",
    label: "فیروزه کویر",
    group: "persian",
    desc: "شن روشن و رگه‌های فیروزه‌ای",
    colors: {
      bg: "#d9c9a8",
      surface: "#fffdf7",
      ink: "#14313a",
      muted: "#546a72",
      accent: "#0c7373",
      accent_ink: "#ffffff",
      amount: "#0a5c66",
      danger: "#b3402b",
      success: "#0c7373",
      line: "#dfd0b2",
    },
  },
  {
    id: "bazaar",
    label: "سرای بازار",
    group: "persian",
    desc: "آجر و طاق‌های راسته بازار",
    colors: {
      bg: "#6b3a2a",
      surface: "#f6e8d8",
      ink: "#2a1a12",
      muted: "#74604f",
      accent: "#9c4f14",
      accent_ink: "#fff6ea",
      amount: "#6b3a10",
      danger: "#a3301f",
      success: "#3f6b3a",
      line: "#e0cbb2",
    },
  },
  {
    id: "anar",
    label: "انار",
    group: "persian",
    desc: "پوست انار تیره با دانه‌های سرخ",
    colors: {
      bg: "#4a0d1a",
      surface: "#fff1f2",
      ink: "#3a0d16",
      muted: "#82525c",
      accent: "#b0123a",
      accent_ink: "#fff0f3",
      amount: "#8c0e2e",
      danger: "#b0123a",
      success: "#2f7a52",
      line: "#f0d2d6",
    },
  },
  {
    id: "yalda",
    label: "شب یلدا",
    group: "persian",
    desc: "شب بلند، هندوانه و ستاره",
    colors: {
      bg: "#1b0b2a",
      surface: "#2a1240",
      ink: "#f6e7ff",
      muted: "#ac97c0",
      accent: "#d63b6a",
      accent_ink: "#fff2f6",
      amount: "#ff7aa2",
      danger: "#ff6b6b",
      success: "#9ae66e",
      line: "#4a2a63",
    },
  },
  {
    id: "nowruz",
    label: "نوروز",
    group: "persian",
    desc: "سبزه بهاری و روشنایی سال نو",
    colors: {
      bg: "#cfe8d5",
      surface: "#ffffff",
      ink: "#16301f",
      muted: "#546c5e",
      accent: "#1f7a4d",
      accent_ink: "#ffffff",
      amount: "#14603c",
      danger: "#b3261e",
      success: "#1f7a4d",
      line: "#cfe0d4",
    },
  },
  {
    id: "termeh",
    label: "ترمه",
    group: "persian",
    desc: "بته‌جقه روی زمینه شرابی و طلا",
    colors: {
      bg: "#4a1f2b",
      surface: "#fdf3e3",
      ink: "#34161f",
      muted: "#74565a",
      accent: "#9c2b33",
      accent_ink: "#fdf0e2",
      amount: "#7d5a12",
      danger: "#9c2b33",
      success: "#3f6b4a",
      line: "#e6d2b4",
    },
  },
  {
    id: "glass",
    label: "شیشه مات",
    group: "modern",
    desc: "کارت یخی و مات روی آسمان غروب",
    colors: {
      bg: "#2b2158",
      surface: "#f4f0ff",
      ink: "#1b1633",
      muted: "#554f72",
      accent: "#5b4bdb",
      accent_ink: "#ffffff",
      amount: "#3b2ea8",
      danger: "#d6455d",
      success: "#1f9d7a",
      line: "#c8bff0",
    },
  },
  {
    id: "swiss",
    label: "سوئیسی",
    group: "modern",
    desc: "شبکه دقیق، سفید و یک قرمز",
    colors: {
      bg: "#eeeeee",
      surface: "#ffffff",
      ink: "#000000",
      muted: "#5f5f5f",
      accent: "#d40000",
      accent_ink: "#ffffff",
      amount: "#000000",
      danger: "#d40000",
      success: "#007a3d",
      line: "#dddddd",
    },
  },
  {
    id: "mono",
    label: "تک‌رنگ",
    group: "modern",
    desc: "فقط سیاه و سفید، بدون حواس‌پرتی",
    colors: {
      bg: "#111111",
      surface: "#ffffff",
      ink: "#000000",
      muted: "#555555",
      accent: "#000000",
      accent_ink: "#ffffff",
      amount: "#000000",
      danger: "#3d3d3d",
      success: "#1f1f1f",
      line: "#e0e0e0",
    },
  },
  {
    id: "pastel",
    label: "پاستل",
    group: "modern",
    desc: "بنفش ملایم و لبه‌های خیلی نرم",
    colors: {
      bg: "#efe6fb",
      surface: "#ffffff",
      ink: "#3a3450",
      muted: "#736c96",
      accent: "#6d55c9",
      accent_ink: "#ffffff",
      amount: "#4a3a9e",
      danger: "#d4557a",
      success: "#3fa08a",
      line: "#e6def7",
    },
  },
  {
    id: "brutal",
    label: "بروتالیست",
    group: "modern",
    desc: "زرد تند، قاب کلفت و سایه سخت",
    colors: {
      bg: "#ffe600",
      surface: "#ffffff",
      ink: "#000000",
      muted: "#3d3d3d",
      accent: "#000000",
      accent_ink: "#ffe600",
      amount: "#000000",
      danger: "#d90000",
      success: "#008a3c",
      line: "#000000",
    },
  },
  {
    id: "soft",
    label: "نرم",
    group: "modern",
    desc: "برجستگی نئومورفیک و سایه دوگانه",
    colors: {
      bg: "#e6e9ef",
      surface: "#e6e9ef",
      ink: "#2a3040",
      muted: "#66708a",
      accent: "#4f6bed",
      accent_ink: "#ffffff",
      amount: "#2a3040",
      danger: "#d64545",
      success: "#2f9e6e",
      line: "#d2d7e0",
    },
  },
  {
    id: "linear",
    label: "خطی",
    group: "modern",
    desc: "مشکی تکنیکال با خطوط باریک نئون",
    colors: {
      bg: "#08090c",
      surface: "#101218",
      ink: "#e8eaf0",
      muted: "#868b9c",
      accent: "#6c8cff",
      accent_ink: "#060812",
      amount: "#b9c6ff",
      danger: "#ff6b7a",
      success: "#4ade80",
      line: "#23262f",
    },
  },
  {
    id: "bank",
    label: "بانکی",
    group: "modern",
    desc: "آبی رسمی و قابل اعتماد",
    colors: {
      bg: "#eef2f7",
      surface: "#ffffff",
      ink: "#10233b",
      muted: "#556579",
      accent: "#0f4c81",
      accent_ink: "#ffffff",
      amount: "#0f4c81",
      danger: "#c0392b",
      success: "#16794a",
      line: "#dbe3ec",
    },
  },
  {
    id: "card",
    label: "کارت بانکی",
    group: "modern",
    desc: "شبیه کارت با چیپ طلایی و نوار",
    colors: {
      bg: "#1a2744",
      surface: "#f4f7fb",
      ink: "#10233d",
      muted: "#5a6e85",
      accent: "#c9a227",
      accent_ink: "#1a1204",
      amount: "#0f4c81",
      danger: "#c0392b",
      success: "#1f8a5a",
      line: "#cdd6e1",
    },
  },
  {
    id: "mint",
    label: "نعنایی",
    group: "modern",
    desc: "سبز نعنا، خنک و سبک",
    colors: {
      bg: "#dff5ee",
      surface: "#ffffff",
      ink: "#10302a",
      muted: "#54746c",
      accent: "#0b7d62",
      accent_ink: "#ffffff",
      amount: "#0b6b55",
      danger: "#c0392b",
      success: "#0b7d62",
      line: "#cfe9e0",
    },
  },
  {
    id: "neon",
    label: "بازار شب",
    group: "dark",
    desc: "نئون شب، شیشه براق و درخشش لبه",
    colors: {
      bg: "#07080d",
      surface: "#12141c",
      ink: "#f4f7ff",
      muted: "#868ea2",
      accent: "#2de2e6",
      accent_ink: "#041618",
      amount: "#ff3cac",
      danger: "#ff5d73",
      success: "#2de2e6",
      line: "#2a3144",
    },
  },
  {
    id: "orbit",
    label: "مدار مبلغ",
    group: "dark",
    desc: "مبلغ وسط یک حلقه نورانی",
    colors: {
      bg: "#0c1220",
      surface: "#151c2e",
      ink: "#eef3ff",
      muted: "#8892ab",
      accent: "#4f8cff",
      accent_ink: "#061018",
      amount: "#7cf0d4",
      danger: "#ff6b81",
      success: "#7cf0d4",
      line: "#2a3550",
    },
  },
  {
    id: "cyber",
    label: "سایبرپانک",
    group: "dark",
    desc: "مجنتا و فیروزه‌ای روی شب شهر",
    colors: {
      bg: "#050308",
      surface: "#120a1e",
      ink: "#f5e9ff",
      muted: "#9a86ba",
      accent: "#ff2e88",
      accent_ink: "#14000a",
      amount: "#00f0ff",
      danger: "#ff4d4d",
      success: "#00f0ff",
      line: "#38214f",
    },
  },
  {
    id: "synth",
    label: "سینت‌ویو",
    group: "dark",
    desc: "غروب شبکه‌ای دهه هشتاد",
    colors: {
      bg: "#150a2e",
      surface: "#21103f",
      ink: "#fdf0ff",
      muted: "#ad94ce",
      accent: "#ff4ecd",
      accent_ink: "#1a0018",
      amount: "#ffd166",
      danger: "#ff5d73",
      success: "#4be0c0",
      line: "#4a2a72",
    },
  },
  {
    id: "aurora",
    label: "شفق قطبی",
    group: "dark",
    desc: "موج‌های سبز و آبی روی شب سرد",
    colors: {
      bg: "#051225",
      surface: "#0c1f36",
      ink: "#e8f4ff",
      muted: "#8da4be",
      accent: "#48e0b0",
      accent_ink: "#002018",
      amount: "#7ad7ff",
      danger: "#ff7a8a",
      success: "#48e0b0",
      line: "#1e3a55",
    },
  },
  {
    id: "galaxy",
    label: "کهکشان",
    group: "dark",
    desc: "آسمان پرستاره و بنفش عمیق",
    colors: {
      bg: "#06031a",
      surface: "#120a33",
      ink: "#ece7ff",
      muted: "#978cc2",
      accent: "#7c3aed",
      accent_ink: "#ffffff",
      amount: "#c4b5fd",
      danger: "#fb7185",
      success: "#34d399",
      line: "#2c1f5c",
    },
  },
  {
    id: "ember",
    label: "اخگر",
    group: "dark",
    desc: "زغال داغ و درخشش نارنجی",
    colors: {
      bg: "#120b08",
      surface: "#1e120c",
      ink: "#ffeadd",
      muted: "#aa8470",
      accent: "#ff6b1a",
      accent_ink: "#1a0800",
      amount: "#ffb37a",
      danger: "#ff5a4d",
      success: "#86d17a",
      line: "#3d2418",
    },
  },
  {
    id: "midnight",
    label: "نیمه‌شب",
    group: "dark",
    desc: "سرمه‌ای آرام برای شب",
    colors: {
      bg: "#0b1220",
      surface: "#131c2e",
      ink: "#e6edf7",
      muted: "#8d9bb2",
      accent: "#2f6ae0",
      accent_ink: "#ffffff",
      amount: "#9ec5ff",
      danger: "#ff7a8a",
      success: "#5ce0a0",
      line: "#253248",
    },
  },
  {
    id: "holo",
    label: "هولوگرام",
    group: "dark",
    desc: "انعکاس رنگین‌کمانی روی فلز تیره",
    colors: {
      bg: "#0a0f14",
      surface: "#101820",
      ink: "#eaf6ff",
      muted: "#89a0b2",
      accent: "#6ee7f0",
      accent_ink: "#04181c",
      amount: "#c4a7ff",
      danger: "#ff8095",
      success: "#6ee7f0",
      line: "#22303c",
    },
  },
  {
    id: "matrix",
    label: "ماتریکس",
    group: "retro",
    desc: "ترمینال سبز و باران کاراکتر",
    colors: {
      bg: "#000700",
      surface: "#02160a",
      ink: "#b8ffcc",
      muted: "#4f9a68",
      accent: "#00ff66",
      accent_ink: "#001a08",
      amount: "#00ff66",
      danger: "#ff5555",
      success: "#00ff66",
      line: "#0d3d20",
    },
  },
  {
    id: "terminal",
    label: "ترمینال کهربایی",
    group: "retro",
    desc: "مانیتور قدیمی با خطوط اسکن",
    colors: {
      bg: "#0d0b06",
      surface: "#16120a",
      ink: "#ffcf7a",
      muted: "#a2793a",
      accent: "#ffb020",
      accent_ink: "#1a0f00",
      amount: "#ffcf7a",
      danger: "#ff6b4a",
      success: "#a8e05f",
      line: "#3b2c12",
    },
  },
  {
    id: "arcade",
    label: "آرکید",
    group: "retro",
    desc: "پیکسل هشت‌بیتی و رنگ‌های جیغ",
    colors: {
      bg: "#10002b",
      surface: "#1c0a3d",
      ink: "#fdf6ff",
      muted: "#ad99cc",
      accent: "#ffdd00",
      accent_ink: "#240046",
      amount: "#00e5ff",
      danger: "#ff2d55",
      success: "#39ff14",
      line: "#45258a",
    },
  },
  {
    id: "vhs",
    label: "نوار ویدیو",
    group: "retro",
    desc: "خطای رنگ و نویز تصویر ویدیویی",
    colors: {
      bg: "#101018",
      surface: "#1a1a26",
      ink: "#f2f2ff",
      muted: "#9494ad",
      accent: "#ff3b6b",
      accent_ink: "#12000a",
      amount: "#36e0ff",
      danger: "#ff3b6b",
      success: "#4be08a",
      line: "#33334a",
    },
  },
  {
    id: "comic",
    label: "کمیک",
    group: "retro",
    desc: "ترام نقطه‌ای و قاب مشکی کارتونی",
    colors: {
      bg: "#ffd93d",
      surface: "#fffdf5",
      ink: "#101010",
      muted: "#4a4a4a",
      accent: "#e23b3b",
      accent_ink: "#fffdf5",
      amount: "#1447c4",
      danger: "#e23b3b",
      success: "#0f8a4a",
      line: "#101010",
    },
  },
  {
    id: "stamp",
    label: "تمبر پستی",
    group: "retro",
    desc: "لبه دندانه‌دار تمبر و مهر باطل",
    colors: {
      bg: "#2f4858",
      surface: "#fdf6ec",
      ink: "#22303a",
      muted: "#5f707c",
      accent: "#1c6b8c",
      accent_ink: "#fdf6ec",
      amount: "#8a3324",
      danger: "#8a3324",
      success: "#2f6b4a",
      line: "#dccfba",
    },
  },
  {
    id: "forest",
    label: "جنگل",
    group: "nature",
    desc: "سایه درخت و سبز عمیق",
    colors: {
      bg: "#0f2417",
      surface: "#f3f7ef",
      ink: "#14261a",
      muted: "#516b58",
      accent: "#2d6a4f",
      accent_ink: "#ffffff",
      amount: "#1b4332",
      danger: "#a03526",
      success: "#2d6a4f",
      line: "#d4e0cd",
    },
  },
  {
    id: "ocean",
    label: "اقیانوس",
    group: "nature",
    desc: "موج‌های آبی و کف روشن",
    colors: {
      bg: "#062a47",
      surface: "#f2f9ff",
      ink: "#0b2740",
      muted: "#4a6780",
      accent: "#0a6ea8",
      accent_ink: "#ffffff",
      amount: "#064e79",
      danger: "#b3402b",
      success: "#0f8a73",
      line: "#d3e5f2",
    },
  },
  {
    id: "desert",
    label: "کویر",
    group: "nature",
    desc: "تپه‌های شنی و آفتاب داغ",
    colors: {
      bg: "#e3c08d",
      surface: "#fff8ec",
      ink: "#3a2a18",
      muted: "#786045",
      accent: "#a1550f",
      accent_ink: "#fff8ec",
      amount: "#7a3f0a",
      danger: "#a33a22",
      success: "#5a7a2f",
      line: "#e8d4b4",
    },
  },
  {
    id: "sakura",
    label: "شکوفه",
    group: "nature",
    desc: "صورتی بهاری و گلبرگ‌های ریز",
    colors: {
      bg: "#f7dfe8",
      surface: "#fffafc",
      ink: "#3d2230",
      muted: "#836072",
      accent: "#c93f6a",
      accent_ink: "#fff5f8",
      amount: "#a12d55",
      danger: "#c0392b",
      success: "#3f8a6a",
      line: "#f2d5df",
    },
  },
  {
    id: "sunset",
    label: "غروب",
    group: "nature",
    desc: "گرمای نارنجی روی افق بنفش",
    colors: {
      bg: "#2a1130",
      surface: "#fff6ee",
      ink: "#331a12",
      muted: "#775548",
      accent: "#cf4b06",
      accent_ink: "#fff6ee",
      amount: "#9c3a06",
      danger: "#c0392b",
      success: "#2f7a5a",
      line: "#f0d9c4",
    },
  },
  {
    id: "vault",
    label: "گاوصندوق",
    group: "luxe",
    desc: "فلز سنگین، پنجره مبلغ و پرچ گوشه",
    colors: {
      bg: "#1a1d22",
      surface: "#2a3038",
      ink: "#e8edf2",
      muted: "#9aa4b0",
      accent: "#d4a017",
      accent_ink: "#1a1404",
      amount: "#f0c14b",
      danger: "#ff6b5a",
      success: "#3dd68c",
      line: "#4a5560",
    },
  },
  {
    id: "silk",
    label: "ابریشم",
    group: "luxe",
    desc: "پارچه نرم و گوشه‌های خیلی گرد",
    colors: {
      bg: "#ead8d2",
      surface: "#fff8f4",
      ink: "#3a2a2c",
      muted: "#756165",
      accent: "#8a4a58",
      accent_ink: "#fff7f4",
      amount: "#6b3a44",
      danger: "#b33b3b",
      success: "#3d7a5a",
      line: "#e2cfc8",
    },
  },
  {
    id: "gold",
    label: "شمش طلا",
    group: "luxe",
    desc: "طلای براق روی مخمل تیره",
    colors: {
      bg: "#1a1508",
      surface: "#2a2210",
      ink: "#f7ecc9",
      muted: "#b09b62",
      accent: "#e6b422",
      accent_ink: "#241a02",
      amount: "#ffd75e",
      danger: "#ff6b5a",
      success: "#b8d95a",
      line: "#4d3f16",
    },
  },
  {
    id: "marble",
    label: "مرمر",
    group: "luxe",
    desc: "سنگ سفید با رگه‌های طلایی",
    colors: {
      bg: "#dcdcd8",
      surface: "#fbfbf9",
      ink: "#1c1c1a",
      muted: "#65655f",
      accent: "#1c1c1a",
      accent_ink: "#f7f7f3",
      amount: "#8a6a1f",
      danger: "#9c2b21",
      success: "#2f6b4a",
      line: "#dcdcd6",
    },
  },
  {
    id: "velvet",
    label: "مخمل",
    group: "luxe",
    desc: "پرده مخمل بنفش و قاب طلایی",
    colors: {
      bg: "#1b0d2a",
      surface: "#2a1440",
      ink: "#f3e9ff",
      muted: "#ad99c2",
      accent: "#c9a227",
      accent_ink: "#1b0d2a",
      amount: "#e8c96a",
      danger: "#ff6b81",
      success: "#7fd6a8",
      line: "#47286b",
    },
  },
  {
    id: "copper",
    label: "مس و زنگار",
    group: "luxe",
    desc: "مس صیقلی با زنگار سبز",
    colors: {
      bg: "#14211f",
      surface: "#f7ece3",
      ink: "#2b1a12",
      muted: "#6a5549",
      accent: "#964f28",
      accent_ink: "#fdf1e8",
      amount: "#7a3d1c",
      danger: "#a3301f",
      success: "#2f7a6b",
      line: "#e0cdbe",
    },
  },
  {
    id: "carbon",
    label: "کربن",
    group: "luxe",
    desc: "الیاف کربن و لبه قرمز اسپرت",
    colors: {
      bg: "#0e0f11",
      surface: "#181a1e",
      ink: "#eef1f5",
      muted: "#8f96a1",
      accent: "#e02020",
      accent_ink: "#ffffff",
      amount: "#f2f4f8",
      danger: "#ff5a4d",
      success: "#38d39f",
      line: "#2b2f36",
    },
  },
];

window.BALE_PAY_LANDING.cssVars = function (colors) {
  const map = {
    bg: "--bg",
    surface: "--surface",
    ink: "--ink",
    muted: "--muted",
    accent: "--accent",
    accent_ink: "--accent-ink",
    amount: "--amount",
    danger: "--danger",
    success: "--success",
    line: "--line",
  };
  return Object.keys(map)
    .map(function (key) {
      return map[key] + ":" + colors[key];
    })
    .join(";");
};

window.BALE_PAY_LANDING.findTheme = function (id) {
  const list = window.BALE_PAY_LANDING.THEMES;
  for (let i = 0; i < list.length; i += 1) {
    if (list[i].id === id) return list[i];
  }
  return list[0];
};
